// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hrpc.proto

package hrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqMeta struct {
	FullMethod           string   `protobuf:"bytes,1,opt,name=full_method,json=fullMethod,proto3" json:"full_method,omitempty"`
	ReqId                uint64   `protobuf:"varint,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	ReqTime              int64    `protobuf:"varint,4,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	BodySize             int32    `protobuf:"varint,5,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	BodyCompressType     int32    `protobuf:"varint,6,opt,name=body_compress_type,json=bodyCompressType,proto3" json:"body_compress_type,omitempty"`
	AuthAccessKey        string   `protobuf:"bytes,7,opt,name=auth_access_key,json=authAccessKey,proto3" json:"auth_access_key,omitempty"`
	AuthData             []byte   `protobuf:"bytes,8,opt,name=auth_data,json=authData,proto3" json:"auth_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMeta) Reset()         { *m = ReqMeta{} }
func (m *ReqMeta) String() string { return proto.CompactTextString(m) }
func (*ReqMeta) ProtoMessage()    {}
func (*ReqMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbe0a179abbe212, []int{0}
}

func (m *ReqMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMeta.Unmarshal(m, b)
}
func (m *ReqMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMeta.Marshal(b, m, deterministic)
}
func (m *ReqMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMeta.Merge(m, src)
}
func (m *ReqMeta) XXX_Size() int {
	return xxx_messageInfo_ReqMeta.Size(m)
}
func (m *ReqMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMeta proto.InternalMessageInfo

func (m *ReqMeta) GetFullMethod() string {
	if m != nil {
		return m.FullMethod
	}
	return ""
}

func (m *ReqMeta) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ReqMeta) GetReqTime() int64 {
	if m != nil {
		return m.ReqTime
	}
	return 0
}

func (m *ReqMeta) GetBodySize() int32 {
	if m != nil {
		return m.BodySize
	}
	return 0
}

func (m *ReqMeta) GetBodyCompressType() int32 {
	if m != nil {
		return m.BodyCompressType
	}
	return 0
}

func (m *ReqMeta) GetAuthAccessKey() string {
	if m != nil {
		return m.AuthAccessKey
	}
	return ""
}

func (m *ReqMeta) GetAuthData() []byte {
	if m != nil {
		return m.AuthData
	}
	return nil
}

type RepMeta struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReqId                uint64   `protobuf:"varint,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	RepTime              int64    `protobuf:"varint,4,opt,name=rep_time,json=repTime,proto3" json:"rep_time,omitempty"`
	BodySize             int32    `protobuf:"varint,5,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	BodyCompressType     int32    `protobuf:"varint,6,opt,name=body_compress_type,json=bodyCompressType,proto3" json:"body_compress_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepMeta) Reset()         { *m = RepMeta{} }
func (m *RepMeta) String() string { return proto.CompactTextString(m) }
func (*RepMeta) ProtoMessage()    {}
func (*RepMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbe0a179abbe212, []int{1}
}

func (m *RepMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepMeta.Unmarshal(m, b)
}
func (m *RepMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepMeta.Marshal(b, m, deterministic)
}
func (m *RepMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepMeta.Merge(m, src)
}
func (m *RepMeta) XXX_Size() int {
	return xxx_messageInfo_RepMeta.Size(m)
}
func (m *RepMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RepMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RepMeta proto.InternalMessageInfo

func (m *RepMeta) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RepMeta) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *RepMeta) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *RepMeta) GetRepTime() int64 {
	if m != nil {
		return m.RepTime
	}
	return 0
}

func (m *RepMeta) GetBodySize() int32 {
	if m != nil {
		return m.BodySize
	}
	return 0
}

func (m *RepMeta) GetBodyCompressType() int32 {
	if m != nil {
		return m.BodyCompressType
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqMeta)(nil), "hrpc.ReqMeta")
	proto.RegisterType((*RepMeta)(nil), "hrpc.RepMeta")
}

func init() { proto.RegisterFile("hrpc.proto", fileDescriptor_1fbe0a179abbe212) }

var fileDescriptor_1fbe0a179abbe212 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcf, 0x4a, 0x33, 0x31,
	0x14, 0xc5, 0xc9, 0xd7, 0xce, 0xbf, 0xfb, 0xb5, 0x28, 0x01, 0x21, 0x22, 0xe2, 0x50, 0x41, 0x66,
	0x21, 0x6e, 0x7c, 0x02, 0xa9, 0x1b, 0x91, 0xd9, 0xc4, 0xee, 0x43, 0x3a, 0xb9, 0x3a, 0x83, 0x1d,
	0x92, 0xc9, 0xa4, 0x8b, 0xe9, 0x23, 0xfa, 0x2c, 0x3e, 0x84, 0xe4, 0xd6, 0x95, 0x0b, 0x57, 0xee,
	0xc2, 0xef, 0x1c, 0x38, 0x39, 0xe7, 0x02, 0xb4, 0xde, 0x35, 0x77, 0xce, 0xdb, 0x60, 0xf9, 0x3c,
	0xbe, 0x57, 0x9f, 0x0c, 0x32, 0x89, 0x43, 0x8d, 0x41, 0xf3, 0x2b, 0xf8, 0xff, 0xba, 0xdf, 0xed,
	0x54, 0x8f, 0xa1, 0xb5, 0x46, 0xb0, 0x92, 0x55, 0x85, 0x84, 0x88, 0x6a, 0x22, 0xfc, 0x0c, 0x52,
	0x8f, 0x83, 0xea, 0x8c, 0x98, 0x95, 0xac, 0x9a, 0xcb, 0xc4, 0xe3, 0xf0, 0x64, 0xf8, 0x39, 0xe4,
	0x11, 0x87, 0xae, 0x47, 0x31, 0x2f, 0x59, 0x35, 0x93, 0x99, 0xc7, 0x61, 0xd3, 0xf5, 0xc8, 0x2f,
	0xa0, 0xd8, 0x5a, 0x33, 0xa9, 0xb1, 0x3b, 0xa0, 0x48, 0x4a, 0x56, 0x25, 0x32, 0x8f, 0xe0, 0xa5,
	0x3b, 0x20, 0xbf, 0x05, 0x4e, 0x62, 0x63, 0x7b, 0xe7, 0x71, 0x1c, 0x55, 0x98, 0x1c, 0x8a, 0x94,
	0x5c, 0xa7, 0x51, 0x59, 0x7f, 0x0b, 0x9b, 0xc9, 0x21, 0xbf, 0x81, 0x13, 0xbd, 0x0f, 0xad, 0xd2,
	0x4d, 0x13, 0xbd, 0xef, 0x38, 0x89, 0x8c, 0x7e, 0xb8, 0x8c, 0xf8, 0x81, 0xe8, 0x33, 0x4e, 0x31,
	0x92, 0x7c, 0x46, 0x07, 0x2d, 0xf2, 0x92, 0x55, 0x0b, 0x99, 0x47, 0xf0, 0xa8, 0x83, 0x5e, 0x7d,
	0x50, 0x5d, 0x47, 0x75, 0x2f, 0x01, 0xd0, 0x7b, 0xeb, 0x55, 0x63, 0x0d, 0x52, 0xdb, 0x44, 0x16,
	0x44, 0xd6, 0xd6, 0x20, 0xbf, 0x86, 0xe5, 0x51, 0xee, 0x71, 0x1c, 0xf5, 0x1b, 0x8a, 0x7f, 0x94,
	0xb6, 0x20, 0x58, 0x1f, 0xd9, 0xaf, 0x8b, 0xb8, 0x1f, 0x8b, 0xb8, 0x3f, 0x5e, 0x64, 0x9b, 0xd2,
	0x21, 0xef, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x89, 0xd0, 0xe4, 0xd6, 0x01, 0x00, 0x00,
}
